[theme]
base = "dark"
primaryColor = "#00c3ff"
backgroundColor = "#0f1117"
secondaryBackgroundColor = "#1e2230"
textColor = "#cccccc"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
